### ISSUE TITLE
yubikey-manager-qt : Depends: python3-yubikey-manager (<= 2) but 2.0.0~ppa1~xenial1 is to be installed

### ISSUE THREAD

**Issue by michaelrobertharmon** [Yubico/yubikey-manager-qt#159]
sudo apt-get install yubikey-manager-qt
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 yubikey-manager-qt : Depends: python3-yubikey-manager (<= 2) but 2.0.0~ppa1~xenial1 is to be installed
                      Recommends: yubikey-manager but it is not going to be installed

**Comment by flugasak** [comment]
I'm running into this exact thing, too. Anybody know any workarounds?

**Comment by emlun** [comment]
Thanks for the report! Looks like the xenial release of version 1.1.0 didn't make it into the PPA. I'll look into it.

**Comment by stefanproell** [comment]
Hello,
I am seeing the same issue. Here are some steps to reproduce with Docker

`docker run --name ubuntu_container --rm -it ubuntu:xenial`

```
root@e854d0345e37:/# apt-get update
root@e854d0345e37:/# apt-get install -y software-properties-common
root@e854d0345e37:/# add-apt-repository ppa:yubico/stable && apt-get update

root@e854d0345e37:/# apt-get install yubikey-manager-qt
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 yubikey-manager-qt : Depends: python3-yubikey-manager (<= 2) but 2.0.0~ppa1~xenial1 is to be installed
                      Recommends: yubikey-manager but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by emlun** [comment]
From version 1.0 onward, we no longer provide Xenial packages for yubikey-manager-qt because of outdated Qt packages. This hasn't caused any breakage before since the 0.5 versions of yubikey-manager-qt were still compatible with the 1.X versions of python3-yubikey-manager, but the 0.5 versions of yubikey-manager-qt available in the PPA are now no longer compatible with the 2.X versions of python3-yubikey-manager.

We recommend Xenial users to uninstall the `yubikey-manager-qt` package and instead use the AppImage available on the [Releases page](https://developers.yubico.com/yubikey-manager-qt/Releases/). Note that you still need the `pcscd` package installed and its daemon running.

Hope that helps, please let us know how it works for you!
