### ISSUE TITLE
Unable to paste OAUTH-HOTP secret into YubiKey Manager prompt

### ISSUE THREAD

**Issue by edmorley** [Yubico/yubikey-manager-qt#187]
Hi

I was hoping to configure my YubiKey 5C Nano's 2nd slot to use OAUTH-HOTP using the YubiKey Manager (version 1.1.1 on OS X), however at the prompt for secret key, it's not possible to paste the secret key (either via Ctrl+V or right click paste), meaning I would have to type it out by hand (which would be error prone, given it's length):

<img width="724" alt="Screenshot 2019-05-12 at 13 28 20" src="https://user-images.githubusercontent.com/501702/57582248-457bef80-74ba-11e9-9e70-b0d5804bdb10.png">

Please could this be fixed?

Many thanks :-)

**Comment by dagheyman** [comment]
Are you sure the secret key is base32 encoded? Because it's not possible to paste it if it isn't. I tried pasting the string `abba` on both Windows and Linux and didn't have any problems.

Maybe it's a bit confusing to silently block pasting like that, the UX around this could probably be improved in future versions.
