### ISSUE TITLE
Support "Yubikey Standard" (Legacy device)

### ISSUE THREAD

**Issue by f0o** [Yubico/yubikey-manager-qt#267]
Hi,

some of us still have lots of these very old but fully functional keys, after some googling and talking to Yubico Support I identified mine as [Yubikey Standard](https://support.yubico.com/hc/en-us/articles/360013656120-YubiKey-Standard) from 2014.

The current Yubikey Manager does not support these whatsoever - However the deprecated Yubikey Personalization Tool still supports them and for the time being still works on recent Linux and Windows 10.

Since YKPersonalizationTool is really old software and officially deprecated, could you add support for legacy devices into Yubikey Manager?

**Comment by dainnilsson** [comment]
Unfortunately I don't have a YubiKey Standard at hand to test with, but this should already work. What problems are you experiencing?

**Comment by f0o** [comment]
No slot configuration is being written to the Yubikeys despite the UI claiming that it did

**Comment by dainnilsson** [comment]
Thanks for the offer, but I can get one from the office the next time I'm there.

We're preparing to release a new version of YubiKey Manager GUI which uses the new ykman 4.0 version. This version uses a completely new backend for OTP programming. If you can download and try one of the development builds, like this one: https://github.com/Yubico/yubikey-manager-qt/actions/runs/646001394

It may very well be that the issue is resolved already. If you're still seeing the problem however, you can try using the command line ykman 4.0 to program the keys, which may provide more information about why it's failing (if indeed it fails).

**Comment by f0o** [comment]
Wow that works without any issues!

Consider this resolved, Thanks :)

**Comment by dainnilsson** [comment]
Awesome! You can expect a "proper" release of that soon!
